# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        ruff check .
    - name: 'Create env file'
      run: |
        touch .env
        echo ENV_STATE=test >> .env
        echo DEV_AWS_REGION_NAME=us-east-1 >> .env
        echo DEV_AWS_ACCESS_KEY_ID=XXX >> .env
        echo DEV_AWS_SECRET_ACCESS_KEY=XXX >> .env
        cat .env
    - name: Test with pytest
      run: |
        pytest
